### PR TITLE
Fix link to VERA Programmer's Reference

### PR DESCRIPTION
**Pull request by lagomorph**

### CODE REVIEW

**Comment by mist64** [comment]
Thanks for looking into this. It is tricky though. If it points to the .html version, it won't work when looking at it on GitHub. If it points to the .md version, the conversion to .html done [here](https://github.com/commanderx16/x16-emulator/blob/master/Makefile#L98) doesn't rewrite the filename, and the link in the .html won't work.

Maybe pandoc can be told to replace links to .md with .html?

(In any case, of course the base filename is wrong in the current version.)

**Comment by lagomorph** [comment]
Yeah, good point. What about something like https://github.com/lagomorph/x16-emulator/commit/ab5dda95ac95f1f0319247dd4e195ce07cc0a823 ?

**Comment by lagomorph** [comment]
> Thanks for looking into this. It is tricky though. If it points to the .html version, it won't work when looking at it on GitHub. If it points to the .md version, the conversion to .html done [here](https://github.com/commanderx16/x16-emulator/blob/master/Makefile#L98) doesn't rewrite the filename, and the link in the .html won't work.
> 
> Maybe pandoc can be told to replace links to .md with .html?
> 
> (In any case, of course the base filename is wrong in the current version.)

Yeah, good point. What about something like https://github.com/lagomorph/x16-emulator/commit/ab5dda95ac95f1f0319247dd4e195ce07cc0a823 ?

**Comment by mist64** [comment]
I'd accept the pandoc-lua pull request. :)

**Comment by lagomorph** [comment]
> I'd accept the pandoc-lua pull request. :)

https://github.com/commanderx16/x16-emulator/pull/114

**Pull request merged**
