### PR TITLE
mouse configuration - Added .Y register

### PR DESCRIPTION
**Pull request by FlightControl-User**
Here a very minimal update as a first try  :-)

### CODE REVIEW

**Comment by FlightControl-User** [comment]
It got generated somehow using my browser, don't know how this came actually. Pls ignore the TOC lines if they are incorrect.

**Comment by FlightControl-User** [comment]
If you want, i can check how these were generated and i'll try to replace the - to *.

**Comment by FlightControl-User** [comment]
@mist64 now it should be more clear what has changed ... if you don't like it, i've found how to disable to TOC generator altogether, which is also an option.

**Comment by mist64** [comment]
Thanks!

**Pull request merged**
